version: "3.8"

services:
  web:
    build:
      context: ./lingo_cube_web
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - server

  server:
    build:
      context: ./lingo_cube_server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=release
